---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cache.de.b3nk4n
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.de.b3nk4n
  resources:
  - memcacheds/finalizers
  verbs:
  - update
- apiGroups:
  - cache.de.b3nk4n
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
